

using FinalYearProject.Data.Context;
using FinalYearProject.Data.Domain.Config;
using FinalYearProject.Data.Domain.Entities;
using FinalYearProject.Data.Domain.Entities.Attributes;
using FinalYearProject.Data.Utilities;
using FinalYearProject.Services.Encryption;
using FinalYearProject.Services.Shared;
using Microsoft.EntityFrameworkCore;
using Serilog;
using System.Net.Http.Json;
using System.Text.Json;

namespace FinalYearProject.Services.UserMgmt;

public class UserMgmtService(
    FileSystemDbContext database,
    FileSystemConfig config,
    IEncryptionService encryptionService,
    IHttpClientFactory httpClientFactory
) : IUserMgmtService
{
    public async Task<ServiceResponse> CreateUserAsync(
        CreateUserRequest request,
        CancellationToken cancellationToken)
    {
        try
        {
            // 1. Check email uniqueness
            bool emailExists = await database.Users
                .AnyAsync(u => u.Email == request.Email, cancellationToken);

            if (emailExists)
                return Response.Conflict("User already exists with this email");

            // 2. Validate attributes exist
            var attributes = await database.Attributes
                .Where(a => request.Attributes.Contains(a.Id))
                .ToListAsync(cancellationToken);

            var missingIds = request.Attributes.Except(attributes.Select(a => a.Id));

            if (missingIds.Any())
            {
                return Response.BadRequest("Invalid attribute(s) provided");
            }

            var attributeNames = attributes
                .Select(a => a.AttributeName)
                .ToArray();

            // 3. Call Python service to generate private key
            var client = httpClientFactory.CreateClient();

            var pythonResponse = await client.PostAsJsonAsync(
                config.ABEBaseURL + "/generate_key",
                new { attributes = attributeNames },
                cancellationToken
            );

            if (!pythonResponse.IsSuccessStatusCode)
            {
                return Response.SystemMalfunction("Failed to generate user key");
            }
            var pythonResult = await pythonResponse.Content.ReadAsStringAsync();

            var keyResponse = JsonSerializer.Deserialize<PythonKeyResponse>(pythonResult);

            var generatedKey = keyResponse?.PrivateKey;
            
            var encryptedPrivateKey = encryptionService.Encrypt(generatedKey);

            string autoGeneratedPassword = Password.Generate;

            // 4. Create user
            var user = new User
            {
                FirstName = request.FirstName,
                LastName = request.LastName,
                Email = request.Email,
                Password = BCrypt.Net.BCrypt.HashPassword(autoGeneratedPassword),
                PrivateKey = encryptedPrivateKey,
                IsActive = true,
                CreatedAt = DateTimeOffset.UtcNow
            };

            // 5. Create user-attribute relationships
            foreach (var attribute in attributes)
            {
                user.UsersAttributes.Add(new UserAttribute
                {
                    User = user,
                    AttributeId = attribute.Id,
                    CreatedAt = DateTimeOffset.UtcNow
                });
            }

            database.Users.Add(user);
            await database.SaveChangesAsync(cancellationToken);

            return Response.Created("User created successfully");
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Error creating user");
            return Response.SystemMalfunction("Something went wrong");
        }
    }

    public async Task<ServiceResponse<UserResponse>> GetUserAsync(
        Guid id,
        CancellationToken cancellationToken)
    {
        var user = await database.Users
            .Include(u => u.UsersAttributes)
                .ThenInclude(ua => ua.Attribute)
            .FirstOrDefaultAsync(u => u.Id == id, cancellationToken);

        if (user == null)
            return Response.NotFound<UserResponse>("User not found", null!);

        var response = new UserResponse(
            user.Id,
            user.FirstName,
            user.LastName,
            user.Email,
            user.UsersAttributes.Select(x => x.Attribute.AttributeName).ToList()
        );

        return Response.Success("User retrieved successfully", response);
    }

    public async Task<ServiceResponse> DeleteUserAsync(
        Guid id,
        CancellationToken cancellationToken)
    {
        var user = await database.Users
            .FirstOrDefaultAsync(u => u.Id == id, cancellationToken);

        if (user == null)
            return Response.NotFound("User not found");

        database.Users.Remove(user);
        await database.SaveChangesAsync(cancellationToken);

        return Response.Success("User deleted successfully");
    }
}
